/* ============================================================================
   EDIAGD — the native shell

   This wraps the DEPLOYED web app rather than bundling a copy of it. The app is
   already mobile-first and ships continuously; a bundled build would mean every
   copy change waits on an App Store review, which is the opposite of why this
   product exists.

   So the shell is thin on purpose. What it adds that a browser tab cannot:
   push notifications, universal/app links, a home-screen presence, and later
   biometric unlock. Everything else is the same Next.js app.

   ---------------------------------------------------------------------------
   LAYOUT
   ---------------------------------------------------------------------------
     capacitor.config.ts   this file — the only Capacitor config
     native/www/           offline fallback shown when the device has no network
     ios/                  generated by `npx cap add ios`     (not committed yet)
     android/              generated by `npx cap add android` (not committed yet)

   `ios/` and `android/` are Capacitor's default locations and are left there so
   `npx cap` works with no flags. They are generated, not authored — the only
   files worth hand-editing inside them are the two Firebase configs, which are
   copied in by `npm run native:sync`.

   ---------------------------------------------------------------------------
   THE URL
   ---------------------------------------------------------------------------
   app.ediagd.ai is the production deployment. It is the default rather than
   something read from the environment at build time, because a native binary
   bakes this value in at `cap sync` — if the env var is missing on whatever
   machine builds the release, the shell silently ships pointing somewhere else.
   A literal is auditable; an env default is a trap.

   NEXT_PUBLIC_APP_URL still overrides, which is what makes it possible to point
   a simulator build at a preview deployment or a laptop.
   ============================================================================ */
import type { CapacitorConfig } from "@capacitor/cli";

export const PRODUCTION_URL = "https://app.ediagd.ai";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? PRODUCTION_URL;

const config: CapacitorConfig = {
  appId: "ai.ediagd.app",
  appName: "EDIAGD",

  /* Offline fallback only. The real app is served from `server.url`. */
  webDir: "native/www",

  server: {
    url: APP_URL,
    /*
     * The webview will not load http:// in release builds, and should not.
     * Left explicit so nobody "fixes" a local-dev problem by turning it on.
     */
    cleartext: false,
    /*
     * Everything on our own host stays inside the webview. Anything else —
     * a support link, a video host — opens in the system browser, which is
     * both an Apple review expectation and the honest behaviour.
     */
    allowNavigation: [
      "app.ediagd.ai",
      "*.ediagd.ai",
      // Supabase auth redirects land back through the project host.
      "*.supabase.co",
    ],
  },

  ios: {
    /*
     * The app is cream-on-navy and already draws its own safe areas via CSS
     * env() — see styles/brand.css. Letting the webview go edge to edge and
     * handling insets in CSS keeps one source of truth for layout.
     */
    contentInset: "never",
    backgroundColor: "#0C1C2C",
    limitsNavigationsToAppBoundDomains: true,
  },

  android: {
    backgroundColor: "#0C1C2C",
    /* Release builds only ever talk to https. */
    allowMixedContent: false,
  },

  plugins: {
    SplashScreen: {
      /*
       * Held until the webview reports the first paint, then faded. A splash
       * that disappears before the app has drawn shows a white flash, which on
       * a navy-branded app reads as a crash.
       */
      launchAutoHide: false,
      backgroundColor: "#0C1C2C",
      androidScaleType: "CENTER_CROP",
      showSpinner: false,
    },
    StatusBar: {
      /* Light glyphs on the navy field. */
      style: "DARK",
      backgroundColor: "#0C1C2C",
      overlaysWebView: true,
    },
    PushNotifications: {
      /*
       * Badge is off. A number on the icon is a debt counter, and this product
       * does not do guilt — see the tone rules in lib/notifications/push-copy.ts.
       */
      presentationOptions: ["alert", "sound"],
    },
  },
};

export default config;
