/* ============================================================================
   EDIAGD — the native shell

   This wraps the DEPLOYED web app rather than bundling a copy of it. The app is
   already mobile-first and ships continuously; a bundled build would mean every
   copy change waits on an App Store review, which is the opposite of why this
   product exists.

   So the shell is thin on purpose. What it adds that a browser tab cannot:
   push notifications, universal/app links, a home-screen presence, and later
   biometric unlock. Everything else is the same Next.js app.

   ---------------------------------------------------------------------------
   LAYOUT
   ---------------------------------------------------------------------------
     capacitor.config.ts   this file — the only Capacitor config
     native/www/           offline fallback shown when the device has no network
     ios/                  committed — TestFlight needs its hand edits kept
     android/              generated by `npx cap add android` (not committed)

   `ios/` and `android/` are Capacitor's default locations and are left there so
   `npx cap` works with no flags.

   ANDROID is generated, not authored — the only files worth hand-editing inside
   it are the Firebase config and the icon set, both put back by
   `npm run native:sync`.

   IOS IS COMMITTED. Shipping to TestFlight needs edits that live nowhere else:
   ITSAppUsesNonExemptEncryption, the version and build numbers, and the signing
   team Xcode writes into the project when Ryan picks it. Regenerating that
   directory would take all of them out, and the damage would show up as a
   rejected upload rather than a build that fails honestly. See .gitignore.

   ---------------------------------------------------------------------------
   THE URL
   ---------------------------------------------------------------------------
   app.ediagd.ai is the production deployment. It is the default rather than
   something read from the environment at build time, because a native binary
   bakes this value in at `cap sync` — if the env var is missing on whatever
   machine builds the release, the shell silently ships pointing somewhere else.
   A literal is auditable; an env default is a trap.

   NEXT_PUBLIC_APP_URL still overrides, which is what makes it possible to point
   a simulator build at a preview deployment or a laptop.
   ============================================================================ */
import type { CapacitorConfig } from "@capacitor/cli";

export const PRODUCTION_URL = "https://app.ediagd.ai";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? PRODUCTION_URL;

const config: CapacitorConfig = {
  appId: "ai.ediagd.app",
  appName: "EDIAGD",

  /* Offline fallback only. The real app is served from `server.url`. */
  webDir: "native/www",

  server: {
    url: APP_URL,
    /*
     * The webview will not load http:// in release builds, and should not.
     * Left explicit so nobody "fixes" a local-dev problem by turning it on.
     */
    cleartext: false,
    /*
     * Everything on our own host stays inside the webview. Anything else —
     * a support link, a video host — opens in the system browser, which is
     * both an Apple review expectation and the honest behaviour.
     */
    allowNavigation: [
      "app.ediagd.ai",
      "*.ediagd.ai",
      // Supabase auth redirects land back through the project host.
      "*.supabase.co",
    ],
  },

  ios: {
    /*
     * The app is cream-on-navy and already draws its own safe areas via CSS
     * env() — see styles/brand.css. Letting the webview go edge to edge and
     * handling insets in CSS keeps one source of truth for layout.
     */
    contentInset: "never",
    backgroundColor: "#0C1C2C",
    limitsNavigationsToAppBoundDomains: true,
  },

  android: {
    backgroundColor: "#0C1C2C",
    /* Release builds only ever talk to https. */
    allowMixedContent: false,
  },

  plugins: {
    SplashScreen: {
      /*
       * BOTH a JS hide and a hard timeout, deliberately.
       *
       * readyShell() hides it as soon as the webview has drawn, which is the
       * good path and keeps the navy field up until there is something to show
       * — a splash that leaves early flashes white, and on a navy app that
       * reads as a crash.
       *
       * launchAutoHide stays TRUE as the floor. The first emulator run had it
       * false and the app opened to a splash that never lifted, because the
       * component that calls hide() was mounted in a layout the login route
       * does not use. Anything that stops that JS from running — a bad deploy,
       * no network on a cold start, an exception before mount — must not be
       * able to brick the app on its own launch screen.
       */
      launchAutoHide: true,
      /*
       * 150ms, not 3000. This number was the launch delay.
       *
       * The splash was being treated as cover for a slow start, but there is
       * nothing underneath it to hide: ios.backgroundColor below paints the
       * WKWebView the same #0C1C2C, and the document's own first bytes set the
       * same navy again. Lifting the splash reveals navy either way — the
       * screen does not change, so there is no flash to protect against.
       *
       * What the long floor DID do was hold the animation behind an opaque
       * layer while it played, so the sequence finished unseen and the launch
       * became a wait followed by a settled mark. Ryan, twice: "there is
       * literally no animation now", "the animation is shorter than the 1.5
       * blank navy screen hold." Both were this value.
       *
       * Not zero: a handful of frames of native splash makes the handoff a
       * dissolve between two identical navy fields rather than a swap that can
       * land mid-frame. launchAutoHide stays true — see above; this is the only
       * thing standing between a JS failure and an app that never opens.
       */
      launchShowDuration: 150,
      backgroundColor: "#0C1C2C",
      androidScaleType: "CENTER_CROP",
      showSpinner: false,
    },
    StatusBar: {
      /* Light glyphs on the navy field. */
      style: "DARK",
      backgroundColor: "#0C1C2C",
      overlaysWebView: true,
    },
    PushNotifications: {
      /*
       * Badge is off. A number on the icon is a debt counter, and this product
       * does not do guilt — see the tone rules in lib/notifications/push-copy.ts.
       */
      presentationOptions: ["alert", "sound"],
    },
  },
};

export default config;
