-- ============================================================================
-- 0004 — intentionally empty.
--
-- This migration used to insert the Doggett CDJR June 2026 export (perf_period,
-- service_line, advisor_op_metric). That is TEST DATA and would have run against
-- any database built from this sequence, including production. It now lives in
-- supabase/seed.sql, which `supabase db reset` applies locally and `db push`
-- never touches.
--
-- The file is kept (rather than deleted) because 0004 is already recorded in the
-- remote migration history; removing it would desync `supabase migration list`.
-- Do not add data here — put it in supabase/seed.sql.
-- ============================================================================

-- no-op
