-- ============================================================================
-- 0007 — intentionally empty.
--
-- This migration used to link a hardcoded test user UUID to Esparza (35122) as
-- an advisor. That is environment-specific TEST DATA and would have run against
-- any database built from this sequence, including production. It now lives in
-- supabase/seed.sql (SECTION 3).
--
-- The file is kept (rather than deleted) because 0007 is already recorded in the
-- remote migration history; removing it would desync `supabase migration list`.
-- Do not add data here — put it in supabase/seed.sql.
-- ============================================================================

-- no-op
