/* ===========================================================================
   0146 — AI-DRAFTED QUESTIONS FOR THE 46 EMPTY MODULES. NOTHING PUBLISHES.
   ===========================================================================

   After 0145, 46 filmed modules carry no questions: Setting up the MPI (9),
   Success Cycle (12), Overcoming Objections modules 3-12 (10), Name Tag (8 —
   Parts 1 and 9 got the CSI seven), Menus (7 lesson modules; the two closers
   carry no quiz by ruling). The standing rule is AI drafts from the lesson,
   Mitch approves in admin, nothing serves until published.

   Every question below was drafted from the FILM'S OWN TRANSCRIPT (whisper
   small.en, 30 Sep 2026, from the published masters) — never from the title,
   never from general knowledge. 4 per module, 184 total: two Multiple Choice,
   one True/False, one scenario in the bank's existing "What Do You Say Next"
   shape. `correct` position is as authored; the quiz page shuffles options
   per advisor per attempt, so the stored letter is not a tell.

     status      'draft'         — moduleRequirementsMet ignores drafts, the
                                   quiz page serves only published, so NOTHING
                                   an advisor sees changes until Mitch acts
     source      'ai_generated'  — provenance, distinguishable from 'authored'
     deck        the track name
     film        the slate title, as "Part N — <spoken title>" (Menus: the
                 film's catalog title)
     module_id + content_id       joined on the film's exact TITLE — the only
                                   key both systems observed

   THERE IS NO ADMIN SCREEN FOR REVIEWING DRAFT QUESTIONS (checked 30 Sep: no
   route under /admin touches quiz_question). Until one exists, the review
   surface is reports/quiz-drafts-<track>.md, generated from these rows.

   On a fresh local none of the films exist and this is a quiet no-op.
   =========================================================================== */

create temporary table _aid (
  source_id  text,
  deck       text,
  film       text,
  film_title text,
  qtype      text,
  question   text,
  option_a   text,
  option_b   text,
  option_c   text,
  option_d   text,
  correct    char(1),
  explanation text,
  qno        int
);

/* ---- SETTING UP THE MPI — Get the Hell Out of Here, Parts 1-9 ---------- */
insert into _aid values
('AID:MPI:P1:Q1','Setting up the MPI','Part 1 — The easiest sell you''ll ever make','Get the Hell Out of Here, Part 1','Multiple Choice','What does Mitch call the easiest sell you''ll ever make?','The one where the customer watches the video and hits approve','A repeat 5,000 mile service','A coupon special','The first sale of the morning','a','A customer who watches that video and hits approve is a sale you didn''t have to call about, negotiate, or close. You just had to set it up right.',1),
('AID:MPI:P1:Q2','Setting up the MPI','Part 1 — The easiest sell you''ll ever make','Get the Hell Out of Here, Part 1','Multiple Choice','What''s wrong with ending write-up on "if anything comes up on the inspection, I''ll give you a buzz"?','It takes too long to say','It sets up a surprise phone call instead of an expected video and an approve button','It sounds too pushy','It skips the business card','b','If that''s your speech, you''re missing the boat — the setup is what makes the approval possible without a call.',2),
('AID:MPI:P1:Q3','Setting up the MPI','Part 1 — The easiest sell you''ll ever make','Get the Hell Out of Here, Part 1','True/False','True or False: You should deliver Mitch''s speech word for word.','True','False','','','b','"You don''t have to say a single thing I say." Build a speech in your own words that leads to more approved recommendations.',3),
('AID:MPI:P1:Q4','Setting up the MPI','Part 1 — The easiest sell you''ll ever make','Get the Hell Out of Here, Part 1','What Do You Say Next','The customer has signed the repair order, you verified their cell and handed over your card. They pick up their keys to leave. What do you say next?','"Good luck with the antique hunt — call me if you need anything."','The MPI setup speech — who''s completing the service, the highlight video, and the green approve button','"We''ll see you around three o''clock."','"Anything else I can help you with today?"','b','The last thing before they leave is the setup for the multi-point inspection — that''s the speech this whole series builds.',4),
('AID:MPI:P2:Q1','Setting up the MPI','Part 2 — The speech','Get the Hell Out of Here, Part 2','Multiple Choice','About how long does the whole setup speech take?','About 30 seconds','About two minutes','About five minutes','As long as it takes','a','"That''s about it, about 30 seconds or so. Now there''s not one wasted word in there."',1),
('AID:MPI:P2:Q2','Setting up the MPI','Part 2 — The speech','Get the Hell Out of Here, Part 2','Multiple Choice','Which items does the speech name as examples of what Hector grades?','Battery cranking amps, tire tread depths and pressures, and the cabin air filter','Wipers, coolant and alignment','Spark plugs, belts and hoses','Whatever is on special that week','a','Named examples set the expectation — when a color shows up next to one, it''s the thing you shared was coming.',2),
('AID:MPI:P2:Q3','Setting up the MPI','Part 2 — The speech','Get the Hell Out of Here, Part 2','True/False','True or False: Some lines of the speech are just politeness.','True','False','','','b','"Every single line is doing a job" — the films that follow take it apart line by line to show what each one does.',3),
('AID:MPI:P2:Q4','Setting up the MPI','Part 2 — The speech','Get the Hell Out of Here, Part 2','What Do You Say Next','A customer asks how they''ll find out if the inspection turns anything up. What do you say next?','"I''ll give you a buzz if anything comes up."','"If there are any items in yellow or red, we''re going to text you those recommendations."','"The cashier will go over it at pickup."','"You can check our portal tonight."','b','The speech promises a text, not a surprise call — and the quickest way back is the green approve button.',4),
('AID:MPI:P3:Q1','Setting up the MPI','Part 3 — Certified technician and completing','Get the Hell Out of Here, Part 3','Multiple Choice','Why say Hector is "completing" your service rather than "working on" it?','Work sounds like effort and a problem; completing sounds like a process already underway that will finish easily','It''s shorter to say','It''s the factory''s required wording','It limits liability','a','"Same certified technician, same vehicle, same amount of time. But the words matter and it paints a completely different picture."',1),
('AID:MPI:P3:Q2','Setting up the MPI','Part 3 — Certified technician and completing','Get the Hell Out of Here, Part 3','Multiple Choice','What does "one of our Toyota Certified Technicians, in your case, Hector" accomplish?','It says the store has a bench and one of them is assigned to you — you''re introducing a person, not naming a tech','It fills time in the speech','It satisfies a manufacturer requirement','It sets up the coupon','a','"It isn''t some guy in the back... You''re not just naming a technician, you''re introducing one. That''s how you sell your team."',2),
('AID:MPI:P3:Q3','Setting up the MPI','Part 3 — Certified technician and completing','Get the Hell Out of Here, Part 3','True/False','True or False: If your technician is Master Certified, keep it simple and just say "the tech."','True','False','','','b','"The higher the title, the more gravitas their recommendations carry. So say it."',3),
('AID:MPI:P3:Q4','Setting up the MPI','Part 3 — Certified technician and completing','Get the Hell Out of Here, Part 3','What Do You Say Next','You know Hector has been with the store twelve years. The customer seems unsure about who''s touching their car. What do you say next?','"The guys in the back are good."','"Hector''s been with us twelve years — his kids go to the school down the road."','"I''ll keep an eye on it personally."','"It''s all computerized now."','b','"If you know a little more, share a little more... Hector is a person, a person they can trust."',4),
('AID:MPI:P4:Q1','Setting up the MPI','Part 4 — The 90-second highlight video','Get the Hell Out of Here, Part 4','Multiple Choice','Why is it a 90-second video?','We live in a TikTok society — a five-minute video gets swiped away; 90 seconds gets watched standing in a line','That''s the camera''s limit','Labor time is billed against it','The manufacturer requires it','a','"90 seconds is something a person will actually watch standing in the line somewhere."',1),
('AID:MPI:P4:Q2','Setting up the MPI','Part 4 — The 90-second highlight video','Get the Hell Out of Here, Part 4','Multiple Choice','Why call it a "highlight" video rather than an inspection video?','Highlights are the good parts — what people actually want to see; that word changes whether they push play','It sounds shorter','It''s the software vendor''s name','It avoids a legal review','a','"It''s not an inspection video. It''s not a walk-through. It''s a highlight video."',2),
('AID:MPI:P4:Q3','Setting up the MPI','Part 4 — The 90-second highlight video','Get the Hell Out of Here, Part 4','True/False','True or False: A customer who watches the video approves more than a customer who doesn''t.','True','False','','','a','"A customer who watches this video is going to appreciate what we do... and approves more than a customer who doesn''t watch it."',3),
('AID:MPI:P4:Q4','Setting up the MPI','Part 4 — The 90-second highlight video','Get the Hell Out of Here, Part 4','What Do You Say Next','A customer shrugs: "you guys just glance at it anyway." What do you say next?','"We do what we can in the time we have."','"He does a really thorough multi-point inspection — we go above and beyond what you came in for."','"The computer checks everything these days."','"I''ll ask him to be extra careful today."','b','"Really thorough" sets the expectation that this is a real inspection, not a glance — you''re sharing what happens when they come to see you.',4),
('AID:MPI:P5:Q1','Setting up the MPI','Part 5 — Name the favourites','Get the Hell Out of Here, Part 5','Multiple Choice','Why name specific items in the speech?','So the grades are expected — when the video shows a color next to those brake pads, it isn''t a surprise and it''s not a sales speech','They''re the most profitable items','They fail most often','They''re the fastest to check','a','"You gave them a preview" — the graded items become the thing you shared was coming.',1),
('AID:MPI:P5:Q2','Setting up the MPI','Part 5 — Name the favourites','Get the Hell Out of Here, Part 5','What Do You Say Next','A teammate wants to add battery cranking amps to their speech, but your technicians don''t consistently measure them. What do you say next?','"Add it — it sounds thorough."','"Only preview what the team actually does — and flag the inconsistent measuring; that''s fixable and worth fixing."','"Say it quietly so nobody holds you to it."','"Skip the speech on busy days."','b','"If you promise something and it doesn''t happen, you just shared with the customer you don''t know what happens in your own shop."',2),
('AID:MPI:P5:Q3','Setting up the MPI','Part 5 — Name the favourites','Get the Hell Out of Here, Part 5','True/False','True or False: Say "green''s really good, red''s really bad" out loud — and red items need to be replaced today.','True','False','','','a','"Green is really good and red is really bad. And when do red items need to be replaced? Today."',3),
('AID:MPI:P5:Q4','Setting up the MPI','Part 5 — Name the favourites','Get the Hell Out of Here, Part 5','Multiple Choice','In the op-code decks, which swap does the speech make when brake fluid is the day''s subject?','Cabin air filter swaps out for the condition of your brake fluid','Tires swap out for alignment','Battery swaps out for coolant','No swap — the three items never change','a','"One swap and you just planted the exact seed that we''re going to cover in 20 minutes or so."',4),
('AID:MPI:P6:Q1','Setting up the MPI','Part 6 — Text it, and speed matters','Get the Hell Out of Here, Part 6','Multiple Choice','Whose recommendations get texted to the customer?','The certified technician''s — he measured it, and you never take credit for anybody else''s work','Yours','The service manager''s','The factory''s','a','"We''re going to text you HIS recommendations. Not yours... It wasn''t you who did that grading."',1),
('AID:MPI:P6:Q2','Setting up the MPI','Part 6 — Text it, and speed matters','Get the Hell Out of Here, Part 6','Multiple Choice','After the recommendations go out, when do you call?','Five to eight minutes later — earlier interrupts the video, later and they''ve moved on with their day','Immediately','After lunch','At the end of the day','a','"You called too early and you interrupted the video. You called too late and they moved on. Five to eight minutes. That''s a good window."',2),
('AID:MPI:P6:Q3','Setting up the MPI','Part 6 — Text it, and speed matters','Get the Hell Out of Here, Part 6','True/False','True or False: Email beats text for getting recommendations watched.','True','False','','','b','"Text beats email every time for these things getting watched. Every single time."',3),
('AID:MPI:P6:Q4','Setting up the MPI','Part 6 — Text it, and speed matters','Get the Hell Out of Here, Part 6','What Do You Say Next','The customer says "just email it to me." What do you say next?','"We don''t really do email."','"Sure, we can email it — and I''ll text it too; texting is the fastest way to get your truck back."','"Email only it is, then."','"I''ll print it for pickup instead."','b','"Sure, we can email it. But train them that texting is best" — you want the fastest channel there is.',4),
('AID:MPI:P7:Q1','Setting up the MPI','Part 7 — The green approve button','Get the Hell Out of Here, Part 7','Multiple Choice','About what share of customers actually hit the green approve button?','About 5%','About half','About 95%','Almost nobody, so skip the line','a','"5% of people will hit that button... but the easiest sell we can make is the one where we don''t have to do a single thing."',1),
('AID:MPI:P7:Q2','Setting up the MPI','Part 7 — The green approve button','Get the Hell Out of Here, Part 7','Multiple Choice','What does the approve-button line train the customer to understand?','Their decision is needed, it''s time-sensitive, and it has consequences — a delayed decision delays their vehicle','That the price is final','That the technician is standing by idle','That phone calls are unwelcome','a','"A delay in the decision means a delay in the process and a delay for getting them their Bronco back."',2),
('AID:MPI:P7:Q3','Setting up the MPI','Part 7 — The green approve button','Get the Hell Out of Here, Part 7','True/False','True or False: Waiting 95 minutes to approve costs the customer nothing — the shop holds their place in line.','True','False','','','b','By then the vehicle is washed or tagged out back — "I gotta get back in line. Do y''all ever get busy? Heck yeah, you do. Every single day."',3),
('AID:MPI:P7:Q4','Setting up the MPI','Part 7 — The green approve button','Get the Hell Out of Here, Part 7','What Do You Say Next','The customer asks "why do I need to press anything? Just call me." What do you say next?','"Company policy, I''m afraid."','"The quickest way to get your Bronco back is to select the green approve button — that alerts Hector in the back to get right on it."','"Fair enough, I''ll call you either way."','"The button is optional."','b','Train the customer: their tap is what puts Hector on it now instead of after the phone tag.',4),
('AID:MPI:P8:Q1','Setting up the MPI','Part 8 — May I give you a quick call?','Get the Hell Out of Here, Part 8','Multiple Choice','What is never put up for discussion?','The multi-point inspection — it''s happening','The price','The pickup time','Which technician is assigned','a','"I didn''t ask you if we could do a multi-point inspection. We''re going to do a multi-point inspection."',1),
('AID:MPI:P8:Q2','Setting up the MPI','Part 8 — May I give you a quick call?','Get the Hell Out of Here, Part 8','Multiple Choice','Why ask permission for the call?','When they say yes — and they will — the call becomes their idea; they agreed to the conversation before there was anything to talk about','It''s a courtesy policy','It''s legally required','It slows the day down usefully','a','"They asked you to call" — which is why the Success Cycle speech can honestly open with "the multi-point inspection that you requested."',2),
('AID:MPI:P8:Q3','Setting up the MPI','Part 8 — May I give you a quick call?','Get the Hell Out of Here, Part 8','True/False','True or False: Every process begins with the previous process and ends on the next one — and that continuity is what customers experience as "these people have it together."','True','False','','','a','The phone call sets up the walk-around, the walk-around sets up this speech, this speech sets up the MPI call, and the MPI call sets up the sale.',3),
('AID:MPI:P8:Q4','Setting up the MPI','Part 8 — May I give you a quick call?','Get the Hell Out of Here, Part 8','What Do You Say Next','On the follow-up call you open with "Hector has completed the multi-point inspection that you requested." Why is that line honest?','Because they signed the repair order','Because they said yes to "do you mind if I give you a quick call?" — you earned that line on the drive before they left','Because the factory requires the inspection','It isn''t — it''s a harmless white lie','b','"That line is not only honest, because it is. You earned that on the drive before they left."',4),
('AID:MPI:P9:Q1','Setting up the MPI','Part 9 — Set up your teammate','Get the Hell Out of Here, Part 9','Multiple Choice','What are the only two things Mitch wants you selling all day, every day?','Yourself and your team','Service and parts','Price and speed','The brand and the building','a','"I only want you to sell two things all day, every day, yourself and your team. This is how to sell your team."',1),
('AID:MPI:P9:Q2','Setting up the MPI','Part 9 — Set up your teammate','Get the Hell Out of Here, Part 9','Multiple Choice','Read the whole speech again — who is it about?','Hector, the certified technician who''s completing the service and gets right on it when approve is selected','You','The customer','The service manager','a','"You set Hector up to be believed before he ever touches the vehicle."',2),
('AID:MPI:P9:Q3','Setting up the MPI','Part 9 — Set up your teammate','Get the Hell Out of Here, Part 9','True/False','True or False: To be fair, you should also walk the customer through how the red decline button works.','True','False','','','b','"Are you going to teach them how to turn you down? Of course you''re not... We''re planting the seed of yes."',3),
('AID:MPI:P9:Q4','Setting up the MPI','Part 9 — Set up your teammate','Get the Hell Out of Here, Part 9','What Do You Say Next','A teammate asks what the point of the whole speech is. What do you say next?','"It speeds up write-up."','"It sets Hector up to be believed before he touches the vehicle — the video gets watched, the recommendations are expected, your teammate is set up."','"It''s for the survey scores."','"Management asked for it."','b','"The video your team shoots, the measurements they take, the whole speech is selling your team."',4);

/* ---- MENUS — the seven lesson modules ----------------------------------- */
insert into _aid values
('AID:MENU:M1:Q1','Menus','The OE Approach — The Maintenance Menu','The OE Approach — The Maintenance Menu','Multiple Choice','Which three rungs of the maintenance ladder "do the work"?','15, 30 and 60 thousand miles','5, 10 and 15 thousand miles','30, 60 and 100 thousand miles','45, 90 and 120 thousand miles','a','45 repeats 15, 90 repeats 30, 120 repeats 60, and 150 is 30 and 60 stacked — learn three milestones and you''ve learned 150,000 miles of intervals.',1),
('AID:MENU:M1:Q2','Menus','The OE Approach — The Maintenance Menu','The OE Approach — The Maintenance Menu','Multiple Choice','What actually changes from brand to brand on the ladder?','The number changes; the item almost never does','The items change; the numbers stay','Both change completely','Nothing changes at all','a','Subaru wants oil at 3,000 severe, Hyundai 3,750, Toyota five, BMW 7,500 — different numbers, same rung.',2),
('AID:MENU:M1:Q3','Menus','The OE Approach — The Maintenance Menu','The OE Approach — The Maintenance Menu','True/False','True or False: You need to memorize all 18 manufacturer schedules.','True','False','','','b','"You have to know one ladder and look up one number."',3),
('AID:MENU:M1:Q4','Menus','The OE Approach — The Maintenance Menu','The OE Approach — The Maintenance Menu','What Do You Say Next','A Subaru owner asks why your oil interval is different from their neighbor''s Toyota. What do you say next?','"Every brand is completely different — it''s hard to keep track."','"Every manufacturer runs the same ladder — the rung is the same, the number is yours; let me look yours up."','"Subarus just need more attention."','"Whatever the sticker says."','b','They''re the same ladder with different rungs — you look up one number rather than guessing.',4),
('AID:MENU:M2:Q1','Menus','The OE Approach — Severe Conditions','The OE Approach — Severe Conditions','Multiple Choice','What does the severe schedule usually do to the normal one?','Cuts it roughly in half — 10,000 becomes five, 30,000 becomes 15','Doubles it','Adds two extra services','Nothing — it''s the same list','a','"Every brand, every line, same idea" — and it''s the most important segment in the module because almost nobody uses it.',1),
('AID:MENU:M2:Q2','Menus','The OE Approach — Severe Conditions','The OE Approach — Severe Conditions','Multiple Choice','Who counts as a severe-service customer?','Most of your customers — short trips, stop-and-go, extended idling, extreme heat or cold, dusty or salty roads, towing','Only off-roaders','Only people who tow','Only commercial fleets','a','"Most of your customers are severe service customers and they have no idea that they are unless we share it."',2),
('AID:MENU:M2:Q3','Menus','The OE Approach — Severe Conditions','The OE Approach — Severe Conditions','True/False','True or False: "Severe" means the customer is abusing the vehicle.','True','False','','','b','"Severe isn''t abuse, Mr. Customer. It''s short trips, stop and go, extreme temperatures, dust and towing."',3),
('AID:MENU:M2:Q4','Menus','The OE Approach — Severe Conditions','The OE Approach — Severe Conditions','What Do You Say Next','The customer says "my book says 10,000 miles." What do you say next?','"The book is out of date."','"Your manual actually has two schedules in it — a normal one and a severe one, and most people have never heard about the second column."','"We recommend more frequent service than the factory."','"Then 10,000 it is."','b','They saw one number in the glove box; nobody ever shared the second column with them.',4),
('AID:MENU:M3:Q1','Menus','The OE Approach — Lifetime Fluid','The OE Approach — Lifetime Fluid','Multiple Choice','A customer says "my manual says lifetime fluid." What''s the first rule?','Don''t argue — they''re right, it does say that','Explain that the manual is wrong','Say the manufacturer is being dishonest','Change the subject to brakes','a','"They read their book correctly... Don''t say anything that makes the customer feel dumb."',1),
('AID:MENU:M3:Q2','Menus','The OE Approach — Lifetime Fluid','The OE Approach — Lifetime Fluid','Multiple Choice','What does "lifetime" actually mean?','The fluid lasts as long as the manufacturer''s warranty — the lifetime of the coverage, not forever','The life of the vehicle','100,000 miles exactly','Until the fluid looks dark','a','"Lifetime of what? Lifetime of the coverage. Your warranty is over. The fluid is still in there."',2),
('AID:MENU:M3:Q3','Menus','The OE Approach — Lifetime Fluid','The OE Approach — Lifetime Fluid','True/False','True or False: Several manufacturers now publish severe-service intervals for fluids they once called lifetime.','True','False','','','a','"It''s true. It''s verifiable." You can share that a lot of manufacturers have softened it — without naming anybody or arguing.',3),
('AID:MENU:M3:Q4','Menus','The OE Approach — Lifetime Fluid','The OE Approach — Lifetime Fluid','What Do You Say Next','You''ve said "you''re right, it does say that" and shared what lifetime means. What comes next?','Quote the price quickly','Bring it local: "in our community, with the traffic and the heat, we think it''s best to change this before something goes wrong."','Show them a competitor''s interval','Offer a discount to settle it','b','"The manual was written for the entire world. You''re the one who knows what this town does to a transmission."',4),
('AID:MENU:M4:Q1','Menus','The OE Approach — Use the Chart','The OE Approach — Use the Chart','Multiple Choice','Why is "the fluid looks dark" a bad basis for a recommendation?','Color is not a condition — many manuals state discoloration alone shouldn''t be the determining factor','It takes too long to check','Customers can''t see the fluid','It''s fine if you sound confident','a','"If you recommend a transmission service because a fluid looked dark and the customer reads that line, you''ve got a problem."',1),
('AID:MENU:M4:Q2','Menus','The OE Approach — Use the Chart','The OE Approach — Use the Chart','Multiple Choice','What does using the chart really buy you?','It moves you out of the conversation — the factory is talking, not the person who benefits from the sale','It makes the pitch longer','It guarantees the sale','It impresses the manager','a','"When you''re guessing, it''s you talking. And you''re the customer''s least favorite voice in the building."',2),
('AID:MENU:M4:Q3','Menus','The OE Approach — Use the Chart','The OE Approach — Use the Chart','True/False','True or False: "I think it''s time" versus "Toyota says it''s time" — the factory wins that argument every time.','True','False','','','a','"Guessing puts your opinion up against the manufacturer''s... so stop entering that argument."',3),
('AID:MENU:M4:Q4','Menus','The OE Approach — Use the Chart','The OE Approach — Use the Chart','What Do You Say Next','You''ve looked up the interval for a customer at 34,000 miles. What do you say next?','"It looks pretty dark under there."','"Toyota wants that done at 30,000 miles under severe conditions — you''re at 34,000."','"In my experience it''s about due."','"Most people do it around now."','b','"That sentence has no opinion in it... There''s nothing there to argue with."',4),
('AID:MENU:M5:Q1','Menus','The Stagger — Why We Spread Them Out','The OE Stagger — Why We Spread Them Out','Multiple Choice','Why do six services pile up at 30,000 miles on the factory schedule?','The manufacturer grouped them at a milestone for printing convenience — they were never all due on the same day','They all genuinely expire together','Dealers add them for revenue','It''s a software error','a','"Brake fluid has been absorbing moisture since the day it was built... Five different services, five different reasons."',1),
('AID:MENU:M5:Q2','Menus','The Stagger — Why We Spread Them Out','The OE Stagger — Why We Spread Them Out','Multiple Choice','Present all five at once versus one — what''s the math nobody runs?','All five realistically sells zero, maybe one; one per visit gives a real shot, and over four visits you can sell them all','All five at once sells more','There''s no difference','Two at a time is the sweet spot','a','"A customer who can say yes to one thing every visit ends up getting on a schedule and doing all five."',2),
('AID:MENU:M5:Q3','Menus','The Stagger — Why We Spread Them Out','The OE Stagger — Why We Spread Them Out','True/False','True or False: Spreading the fluids out is a sales technique rather than an accuracy improvement.','True','False','','','b','"Spreading them out isn''t a sales technique. It''s just more accurate" — the five were never all due the same day.',3),
('AID:MENU:M5:Q4','Menus','The Stagger — Why We Spread Them Out','The OE Stagger — Why We Spread Them Out','What Do You Say Next','A customer at 30,000 miles goes pale at the list of six services. What do you say next?','"The factory says all six, so all six."','"Offering one service each visit keeps you on budget and still gets everything done — these were never all due on the same day."','"We can skip them all this time."','"Pick whichever three you like."','b','Same five fluids, same year, spread across visits they were already going to make anyway.',4),
('AID:MENU:M6:Q1','Menus','The OE Stagger — The Order and Why','The OE Stagger — The Order and Why','Multiple Choice','What is the stagger order?','Brake fluid, differential, power steering, transmission, coolant','Coolant, transmission, brake fluid, differential, power steering','Transmission first, then whatever''s cheapest','Any order — it doesn''t matter','a','"Five fluids, five visits, and the order is not random."',1),
('AID:MENU:M6:Q2','Menus','The OE Stagger — The Order and Why','The OE Stagger — The Order and Why','Multiple Choice','Why does brake fluid go first — and it''s not close?','It protects the person, it''s due regardless of the odometer because it absorbs moisture even parked, and it''s the easiest yes','It''s the most expensive','It''s the fastest service','It''s the only one with a dash light','a','"Eight feet shorter stopping for cars, 13 feet for trucks — that''s the strongest number you own."',2),
('AID:MENU:M6:Q3','Menus','The OE Stagger — The Order and Why','The OE Stagger — The Order and Why','True/False','True or False: Power steering sits third because most manufacturers publish no interval for it — if you don''t recommend it, it never happens.','True','False','','','a','"No mileage trigger, nothing on the schedule, no dash light... and it''s cheap enough to ride along" — but verify the reservoir first; electronic power steering has no fluid.',3),
('AID:MENU:M6:Q4','Menus','The OE Stagger — The Order and Why','The OE Stagger — The Order and Why','What Do You Say Next','A truck owner asks whether the differential service really applies to them. What do you say next?','"Everyone needs it, every time."','"Do you tow, launch a boat, drive gravel? One question sorts it — used that way, it''s a layup; if not, we skip it and move down the list."','"Only if the fluid looks dark."','"The factory doesn''t care either way."','b','"It qualifies itself... And that''s a real answer, not a stall."',4),
('AID:MENU:M7:Q1','Menus','The OE Stagger — Running It','The OE Stagger — Running It','Multiple Choice','What''s the cadence of the stagger?','One fluid per visit','All five, once a year','Two per visit until done','Whatever fits the ticket','a','"A customer who can say yes to one thing every visit ends up getting on a schedule and doing all five."',1),
('AID:MENU:M7:Q2','Menus','The OE Stagger — Running It','The OE Stagger — Running It','Multiple Choice','What is "the engine" that makes the whole stagger work?','The notation — every no goes down as deferred, not declined, with mileage and date; next visit''s opening line lives in that note','The pitch itself','The coupon book','The chart','a','"Mr. Smith, we took care of your brake fluid back in March. This visit, I want to talk about your differentials. That''s not a pitch. That''s continuity."',2),
('AID:MENU:M7:Q3','Menus','The OE Stagger — Running It','The OE Stagger — Running It','True/False','True or False: If the customer says yes quickly, add the next fluid on while you''ve got them.','True','False','','','b','"Take the yes... You just showed a customer that when you recommended something, it''s the one thing that is actually due. That''s worth more than a second sale today."',3),
('AID:MENU:M7:Q4','Menus','The OE Stagger — Running It','The OE Stagger — Running It','What Do You Say Next','The customer says no to the differential service. What do you do next?','Repitch it with more urgency','Back off, note it deferred, and move down the list next visit — the multi-point inspection is coming anyway','Offer it at a discount','Note it declined and drop it forever','b','"Here''s what a customer learns when you repitch a no: that saying no doesn''t work — and the only way to end it is to stop coming here."',4);

/* ---- SUCCESS CYCLE — Parts 1-12 ----------------------------------------- */
insert into _aid values
('AID:SC:P1:Q1','Success Cycle','Part 1 — Not a Rut Team','Success Cycle, Part 1, Not a Rut Team','Multiple Choice','What is a Success Cycle?','Use the same speech pattern for every presentation: you get good fast, good makes you confident, the customer picks up on it, they buy more, and you get more confident','A monthly sales contest','The CRM follow-up sequence','The service lane rotation schedule','a','One speech to present any product to any customer — the cycle is what the repetition builds.',1),
('AID:SC:P1:Q2','Success Cycle','Part 1 — Not a Rut Team','Success Cycle, Part 1, Not a Rut Team','Multiple Choice','What are "Rut Teams"?','Doing the same bad stuff over and over and getting the same bad results — same effort, opposite direction','Teams that skip training','New hires in their first month','Stores with slow Tuesdays','a','Same effort as a Success Cycle, pointed the wrong way.',2),
('AID:SC:P1:Q3','Success Cycle','Part 1 — Not a Rut Team','Success Cycle, Part 1, Not a Rut Team','True/False','True or False: The goal of this class is to learn to sell exactly like Mitch.','True','False','','','b','"I don''t want you selling like me. I want you selling like you. We got to find your voice."',3),
('AID:SC:P1:Q4','Success Cycle','Part 1 — Not a Rut Team','Success Cycle, Part 1, Not a Rut Team','What Do You Say Next','A teammate says "just give me the exact script to memorize." What do you say next?','"Here, word for word — never deviate."','"It''s a framework and a lot of opinions about words — but it''s your speech, written in your words."','"Scripts are banned here."','"Ask the manager for the official one."','b','"It''s the trainer''s job to get the greatness out of every single person in front of them. Not to impose their will."',4),
('AID:SC:P2:Q1','Success Cycle','Part 2 — Vocabulary That Sails','Success Cycle, Part 2, Vocabulary That Sails','Multiple Choice','In Mitch''s restaurant terms, what is a "detail"?','Peppercorn crusted','Steak or chicken','How you want it cooked','The bill','a','An option is steak or chicken, a choice is how it''s cooked, a detail is peppercorn crusted — "dive into the details, baby."',1),
('AID:SC:P2:Q2','Success Cycle','Part 2 — Vocabulary That Sails','Success Cycle, Part 2, Vocabulary That Sails','Multiple Choice','What replaces "price" and "cost"?','Total, or total investment — never a "grand total"','Fee','Charge','Amount due','a','A pricey ring and a costly battle both sound like a lot — "and you ain''t Drew Carey, and this ain''t The Price Is Right."',2),
('AID:SC:P2:Q3','Success Cycle','Part 2 — Vocabulary That Sails','Success Cycle, Part 2, Vocabulary That Sails','True/False','True or False: "Explaining" things lands well with every customer.','True','False','','','b','Never explain — go over the options, choices and details instead.',3),
('AID:SC:P2:Q4','Success Cycle','Part 2 — Vocabulary That Sails','Success Cycle, Part 2, Vocabulary That Sails','What Do You Say Next','You''re about to say "let me tell you what''s going on with your Camry." What do you say instead?','"Let me share with you the status of your Camry."','"Let me explain what''s wrong with your Camry."','"Here''s what you need to do."','"Listen carefully."','a','"Nobody likes to be told what to do... words like share start to build a relationship with your customers."',4),
('AID:SC:P3:Q1','Success Cycle','Part 3 — More Vocabulary','Success Cycle, Part 3, More Vocabulary','Multiple Choice','Why say "fuel efficiency" instead of "gas mileage"?','You don''t control how anybody drives — gas mileage rides on the pedal; fuel efficiency is how the vehicle runs, and you can stand by it','It sounds more scientific','It''s the factory term','They mean exactly the same thing','a','"You can''t promise better gas mileage... fuel efficiency, restoration of horsepower, better acceleration — all true and things you can stand by."',1),
('AID:SC:P3:Q2','Success Cycle','Part 3 — More Vocabulary','Success Cycle, Part 3, More Vocabulary','Multiple Choice','What replaces "problems" and "issues"?','Items of concern','Troubles','Faults','Defects','a','"Item of concern, much like the word share, starts to build empathy with the customer."',2),
('AID:SC:P3:Q3','Success Cycle','Part 3 — More Vocabulary','Success Cycle, Part 3, More Vocabulary','True/False','True or False: "Flush" is a good, vivid word for a fluid service.','True','False','','','b','"When most people hear the word flush, they think of a toilet" — it''s a fluid exchange or a service.',3),
('AID:SC:P3:Q4','Success Cycle','Part 3 — More Vocabulary','Success Cycle, Part 3, More Vocabulary','What Do You Say Next','You''re about to point a customer to "the waiting area." What do you say instead?','"Make yourself comfortable in our lounge."','"The waiting room is through there."','"Take a seat wherever."','"The holding area is on the left."','a','"Waiting areas are at the doctor''s office... We don''t want anybody thinking about a root canal when they''re hanging out in our lounge."',4),
('AID:SC:P4:Q1','Success Cycle','Part 4 — Green Yellow Red','Success Cycle, Part 4, Green Yellow Red','Multiple Choice','How should a measurement be presented?','The number and the color — the number shows what you measured, the color shares what it means','Millimeters only, for precision','The color only, to keep it simple','As a percentage of wear','a','"Your brake pads are at six millimeters, they''re in the green" — a number by itself is too technical.',1),
('AID:SC:P4:Q2','Success Cycle','Part 4 — Green Yellow Red','Success Cycle, Part 4, Green Yellow Red','Multiple Choice','When do red brakes need to be replaced?','Today','At three millimeters','By the next visit','Within the month','a','"Don''t say at three millimeters. What day? The answer is now."',2),
('AID:SC:P4:Q3','Success Cycle','Part 4 — Green Yellow Red','Success Cycle, Part 4, Green Yellow Red','True/False','True or False: Yellow means "we''ll keep an eye on it."','True','False','','','b','Yellow is the traffic light — brief. "Based on how you drive, by your next visit they''re going to be in the red."',3),
('AID:SC:P4:Q4','Success Cycle','Part 4 — Green Yellow Red','Success Cycle, Part 4, Green Yellow Red','What Do You Say Next','The customer''s brakes graded yellow and they ask what they should do. What do you say next?','"They''re fine for now."','"We can take care of them now, or you can let it go into the red — and I don''t want your brakes getting into the red. The choice is yours."','"You must do them today."','"Wait for the light to come on."','b','The choice is theirs; your job is to make sure it''s an informed one — don''t make the decision for the customer.',4),
('AID:SC:P5:Q1','Success Cycle','Part 5 — The 6 Stages','Success Cycle, Part 5, The 6 Stages','Multiple Choice','What are the six stages?','Plan, pitch, feature, benefit, common objection, overcoming the objection','Greet, qualify, present, close, follow up, review','Inspect, price, text, call, close, deliver','Plan, present, pause, push, pivot, part','a','"One repeatable pattern for every customer, every presentation, every time."',1),
('AID:SC:P5:Q2','Success Cycle','Part 5 — The 6 Stages','Success Cycle, Part 5, The 6 Stages','Multiple Choice','What goes into the plan?','Check history and deferrals, count the visits, read the old MPI, confirm and understand the parts and warranty, look for piggybacks, and decide what to hand or send them','Just the price and the time','The technician''s schedule','The coupon calendar','a','"If you fail to plan, you plan to fail" — and counting the visits out loud makes loyalty feel rewarded.',2),
('AID:SC:P5:Q3','Success Cycle','Part 5 — The 6 Stages','Success Cycle, Part 5, The 6 Stages','True/False','True or False: Piggyback sales are gouging.','True','False','','','b','"Piggybacks are not gouging people. It''s convenience. We''re already there. It''s already open."',3),
('AID:SC:P5:Q4','Success Cycle','Part 5 — The 6 Stages','Success Cycle, Part 5, The 6 Stages','What Do You Say Next','You''re about to pitch an alignment to a customer in the lounge. What do you bring with you?','Nothing — travel light','Something to hand them: the printout, the color-coded inspection, a brochure, maybe the dirty filter','Your phone with the invoice open','A seat, to settle in','b','The plan includes what you''re going to hand them or send them — real information in their hands.',4),
('AID:SC:P6:Q1','Success Cycle','Part 6 — More Staging','Success Cycle, Part 6, More Staging','Multiple Choice','What are the three moves before you pitch?','Sell yourself, sell your team, and say thanks — and mean it','Smile, stand tall, speak slowly','Plan, price, close','Coupon, warranty, financing','a','"Thank him before you pitch... Say thank you 40 times a day. That is not an exaggeration."',1),
('AID:SC:P6:Q2','Success Cycle','Part 6 — More Staging','Success Cycle, Part 6, More Staging','Multiple Choice','When do the consequences — "if left ignored" — come into the pitch?','Second, only if they say no; reward action comes first','First, to set the stakes','Never','Only in the text message','a','"Skip the scare tactics... There''s no money in selling from fear unless you write thrillers."',2),
('AID:SC:P6:Q3','Success Cycle','Part 6 — More Staging','Success Cycle, Part 6, More Staging','True/False','True or False: Thank the customer at the end of the pitch, once they''ve said yes.','True','False','','','b','"Thank him up front. Not at the end... Count the visits out loud."',3),
('AID:SC:P6:Q4','Success Cycle','Part 6 — More Staging','Success Cycle, Part 6, More Staging','What Do You Say Next','A teammate opens every call with "man, I''ve got some bad news for you today." What do you say next?','"At least it''s honest."','"Don''t anti-sell — we''ve got GREAT news: we found it, Hector graded it, and we can take care of it."','"Bad news first is a proven technique."','"Say it faster so it stings less."','b','"Be positive, man. Be upbeat. Don''t anti-sell."',4),
('AID:SC:P7:Q1','Success Cycle','Part 7 — Features and Benefits','Success Cycle, Part 7, Features and Benefits','Multiple Choice','What''s the difference between a feature and a benefit?','A feature is what the part or service does to the vehicle; a benefit is what it does for the customer','A feature is the price; a benefit is the discount','They''re interchangeable','A benefit is for the technician','a','"Features are for the head. Benefits are for the heart. You need both to properly close customers."',1),
('AID:SC:P7:Q2','Success Cycle','Part 7 — Features and Benefits','Success Cycle, Part 7, Features and Benefits','Multiple Choice','What question comes before the feature and benefit?','"Are you familiar with our brake fluid exchanges?" — it''s respectful and it hands them the floor','"Can I be honest with you?"','"Do you want the good news or the bad news?"','"How much were you hoping to spend?"','a','About 90% say no — then you educate. It also removes the biggest objection early: not knowing why.',2),
('AID:SC:P7:Q3','Success Cycle','Part 7 — Features and Benefits','Success Cycle, Part 7, Features and Benefits','True/False','True or False: If the customer says they ARE familiar with the service, walk them through it anyway to be thorough.','True','False','','','b','"Don''t reteach somebody who already knows something" — share that it''s great they know, and skip straight for the close.',3),
('AID:SC:P7:Q4','Success Cycle','Part 7 — Features and Benefits','Success Cycle, Part 7, Features and Benefits','What Do You Say Next','You''ve named the cabin air filter feature — old one out, fresh factory filter in. What''s the benefit you share next?','"It''s a very popular service."','"Cleaner air for you and the kids — and less strain on your AC system."','"The factory recommends it."','"It only takes ten minutes."','b','"Everything we do should be built on two things: saving you money and keeping you safe."',4),
('AID:SC:P8:Q1','Success Cycle','Part 8 — Anticipate the No','Success Cycle, Part 8, Anticipate the No','Multiple Choice','What''s the difference between price and budget?','Price is the total dollar amount; budget is when they can pay for it — value answers price, financing answers budget','They''re the same objection','Budget means they want it cheaper','Price means monthly payments','a','"Confuse the two and you''ll discount a customer that was just needing a payment plan."',1),
('AID:SC:P8:Q2','Success Cycle','Part 8 — Anticipate the No','Success Cycle, Part 8, Anticipate the No','Multiple Choice','What is this stage, really?','The listening portion — figure out which objection you''re actually hearing before you answer the one you expected','The rebuttal script','The discount decision','The close','a','"It''s not the answer. It''s the listening portion."',2),
('AID:SC:P8:Q3','Success Cycle','Part 8 — Anticipate the No','Success Cycle, Part 8, Anticipate the No','True/False','True or False: You write down the likely no before you ever make the call.','True','False','','','a','"You go through all of these steps before you go to that lounge, before you call someone on the phone."',3),
('AID:SC:P8:Q4','Success Cycle','Part 8 — Anticipate the No','Success Cycle, Part 8, Anticipate the No','What Do You Say Next','The customer says "that''s too expensive AND I can''t pay for it today." What do you hear?','One objection: money','Two different problems — value answers the price half, financing and installments answer the budget half','A polite no','A negotiation opening','b','"It''s too expensive and I can''t pay for it today — that''s not the same problem."',4),
('AID:SC:P9:Q1','Success Cycle','Part 9 — More on Overcoming Objections','Success Cycle, Part 9, More on Overcoming Objections','Multiple Choice','For a money objection, what''s the order of answers?','Value first, then financing, then a coupon, then the warranty','Discount first, then value','Warranty first, always','Whatever''s fastest','a','"By taking advantage of this today, you qualify for a 30,000 mile warranty" — the warranty is a strong way to overcome money.',1),
('AID:SC:P9:Q2','Success Cycle','Part 9 — More on Overcoming Objections','Success Cycle, Part 9, More on Overcoming Objections','Multiple Choice','The customer has to call the decision maker. What do you do?','Load them with information — the mileage, what''s green, what''s red — so the person at home has an easy decision','Ask for the decision maker''s number','Wait for tomorrow','Lower the price preemptively','a','"Load their lips exactly like you would as an advisor to pitch it to them."',2),
('AID:SC:P9:Q3','Success Cycle','Part 9 — More on Overcoming Objections','Success Cycle, Part 9, More on Overcoming Objections','True/False','True or False: Never give up after the first no, and always give up after the second.','True','False','','','a','"No badgering, no bullying, no shame selling... thank them, note it as deferred and follow up later."',3),
('AID:SC:P9:Q4','Success Cycle','Part 9 — More on Overcoming Objections','Success Cycle, Part 9, More on Overcoming Objections','What Do You Say Next','The customer says "I can do it myself." What do you say next?','"You really can''t."','"You can — and here''s what you''d be giving up: the warranty, certified installation, and your Saturday."','"Then why did you come here?"','"Parts alone cost more than our service."','b','"Remind them that they can buy the parts themselves and share what they''d be giving up."',4),
('AID:SC:P10:Q1','Success Cycle','Part 10 — Anatomy of the Speech','Success Cycle, Part 10, Anatomy of the Speech','Multiple Choice','About how long does the whole speech run?','About 70 seconds','About 30 seconds','About three minutes','About five minutes','a','The whole call, from "you got a sec?" to "all I need is your authorization" — about 70 seconds.',1),
('AID:SC:P10:Q2','Success Cycle','Part 10 — Anatomy of the Speech','Success Cycle, Part 10, Anatomy of the Speech','Multiple Choice','How does the speech end?','With a declarative statement — "all I need is your authorization" — and then you stop talking','With a question, to invite dialogue','With the price repeated twice','With a thank-you','a','"Never end your presentation with a question... often the first person who talks loses."',2),
('AID:SC:P10:Q3','Success Cycle','Part 10 — Anatomy of the Speech','Success Cycle, Part 10, Anatomy of the Speech','True/False','True or False: "Are you familiar with our brake fluid exchanges?" belongs mid-speech, not at the end.','True','False','','','a','"There are times for questions. That''s in the middle" — it clears the they-don''t-know-why objection before the close.',3),
('AID:SC:P10:Q4','Success Cycle','Part 10 — Anatomy of the Speech','Success Cycle, Part 10, Anatomy of the Speech','What Do You Say Next','You''ve bundled the brake fluid exchange with the 5,000 mile service: "that brings your total investment today to 568.98, and we can still have everything done by three o''clock." What do you say next?','"Does that sound okay to you?"','"All I need is your authorization." Then silence.','"I know it''s a lot."','"Shall I email a breakdown?"','b','Time on the clock, one total, and the declarative ask — then stop talking.',4),
('AID:SC:P11:Q1','Success Cycle','Part 11 — The Repair Call','Success Cycle, Part 11, The Repair Call','Multiple Choice','How does a repair call differ from a maintenance call?','Cover their concern first — diagnosis, price, time, authorization — then thank them and go over the multi-point inspection: two closes','It skips the inspection results','It has no close','It''s exactly the same','a','"You got to cover what happened on their concern first, and then you talk about maintenance. So it''s two closes."',1),
('AID:SC:P11:Q2','Success Cycle','Part 11 — The Repair Call','Success Cycle, Part 11, The Repair Call','Multiple Choice','How do you name a service with several parts in it?','Use your store name — "an XYZ Motors brake job" — because your pads, rotors and quiet treatment are different','Use the factory part numbers','Keep it generic to avoid questions','Let the technician name it','a','"Hector recommends we do an XYZ Motors brake job... that''s different."',2),
('AID:SC:P11:Q3','Success Cycle','Part 11 — The Repair Call','Success Cycle, Part 11, The Repair Call','True/False','True or False: A customer already spending $3,000 on a repair shouldn''t be offered wiper blades.','True','False','','','b','"That''s exactly when you offer someone wipers... the worst thing you can do is ignore the rest of the needs of their vehicle."',3),
('AID:SC:P11:Q4','Success Cycle','Part 11 — The Repair Call','Success Cycle, Part 11, The Repair Call','What Do You Say Next','The customer has no visit history on file. What do you say next?','Skip the thanks and get to the diagnosis','"First, I want to thank you for bringing your F-150 to us in your time of need."','"Looks like you''re new here."','"Our records show nothing about you."','b','"No history? Thank them anyway."',4),
('AID:SC:P12:Q1','Success Cycle','Part 12 — Your song, Go Sing It','Success Cycle, Part 12, Your song, Go Sing It','Multiple Choice','What''s the point of the national anthem examples — Hendrix, Marvin Gaye, Lady Gaga?','Same song, different voices — and what they had in common is they went out there and sang it','Practice the actual anthem','Volume wins','Only professionals should perform','a','"Riff all you want, but keep the bones" — the jazz band always comes back to the beat.',1),
('AID:SC:P12:Q2','Success Cycle','Part 12 — Your song, Go Sing It','Success Cycle, Part 12, Your song, Go Sing It','Multiple Choice','Where do you pitch, and why?','Take them from the lounge to your kiosk — you don''t share anybody''s business, and the customer should feel the song was written for them','In the lounge, where they''re comfortable','On the drive, to save time','At the cashier','a','"I don''t want everybody to hear it when you''re pitching it to one person."',2),
('AID:SC:P12:Q3','Success Cycle','Part 12 — Your song, Go Sing It','Success Cycle, Part 12, Your song, Go Sing It','True/False','True or False: Overthink the speech during planning, never while you''re pitching it.','True','False','','','a','"Think before, not during... You got to pitch it naturally."',3),
('AID:SC:P12:Q4','Success Cycle','Part 12 — Your song, Go Sing It','Success Cycle, Part 12, Your song, Go Sing It','What Do You Say Next','Your speech hasn''t worked for a day and a half. What do you do next?','Scrap it and start over','Tweak something — not everything — and keep running it','Go back to winging it','Borrow a teammate''s speech wholesale','b','"You don''t have to change everything. Just tweak something... run it over and over and it will create a success cycle."',4);

/* ---- OVERCOMING OBJECTIONS — modules 3-12, the Selling Skills films ------ */
insert into _aid values
('AID:OO:M3:Q1','Overcoming Objections','Part 1 — Watch the video first','Selling Skills, Part 1','Multiple Choice','Before you pick up the phone, what do only the good advisors do?','Watch the multi-point inspection video the customer just received','Rehearse the price three times','Check the commission sheet','Text the technician for a summary','a','"A bad video can scare off a customer faster than a good video can reel them in" — know before you call, not after they bring it up.',1),
('AID:OO:M3:Q2','Overcoming Objections','Part 1 — Watch the video first','Selling Skills, Part 1','Multiple Choice','What''s the rule on coupons?','Offer it to one customer, offer it to all — anything else is two-tier pricing, and customers talk','Save them for closing tough deals','Never mention them first','Only on advertised specials','a','"If you''re not a coupon person, then don''t be. Just be consistent."',2),
('AID:OO:M3:Q3','Overcoming Objections','Part 1 — Watch the video first','Selling Skills, Part 1','True/False','True or False: Reporting a technician''s consistently bad videos to your manager is telling on him.','True','False','','','b','"That''s not telling on anybody. That''s protecting every customer who''s about to watch one and every advisor who has to call them afterwards."',3),
('AID:OO:M3:Q4','Overcoming Objections','Part 1 — Watch the video first','Selling Skills, Part 1','What Do You Say Next','You''re about to dial. What have you already done?','Nothing — spontaneity sells','Watched the video, written down the certified technician''s name, checked for coupons, and run plan, pitch, feature, benefit, objection, overcome','Pulled up the payment calculator','Asked the tech what to push','b','"Plan smarter and make the calls easier."',4),
('AID:OO:M4:Q1','Overcoming Objections','Part 2 — Send the link before you call','Selling Skills, Part 2','Multiple Choice','When does the financing link go out?','Before the call — at write-up, in the text with the inspection video','After the customer objects to the price','At the cashier','Only when they ask','a','"The first advisor is reacting. The second advisor planned for it."',1),
('AID:OO:M4:Q2','Overcoming Objections','Part 2 — Send the link before you call','Selling Skills, Part 2','Multiple Choice','What does sending the link with every inspection do?','It makes financing normal — nobody feels singled out, nobody feels like they need it; it''s just an option already on their phone','It raises the average ticket automatically','It replaces the phone call','It satisfies a lender requirement','a','"Financing isn''t just a last ditch effort to save the deal. It''s just a part of how you do your business."',2),
('AID:OO:M4:Q3','Overcoming Objections','Part 2 — Send the link before you call','Selling Skills, Part 2','True/False','True or False: Financing is a rescue you reach for once the deal stalls.','True','False','','','b','Flip it — send the link before you call, and the rescue never has to sound like one.',3),
('AID:OO:M4:Q4','Overcoming Objections','Part 2 — Send the link before you call','Selling Skills, Part 2','What Do You Say Next','The customer says "I wasn''t looking to spend that much today." What do you say next?','"I understand, maybe next time."','"That''s exactly why I already sent you the link — open it up, it takes about 90 seconds to apply."','"Let me see what I can discount."','"It''s cheaper than a new car."','b','The link is already on their phone because you planned for this exact sentence.',4),
('AID:OO:M5:Q1','Overcoming Objections','Part 3 — Hand them something','Selling Skills, Part 3','Multiple Choice','What is the "transference of power" problem?','You hold their car, their keys and their afternoon — and a customer who feels powerless says no a little just to get back at you','Technicians outrank advisors','Managers must approve every quote','The customer holds all the cards','a','"Give some power back. Hand them something."',1),
('AID:OO:M5:Q2','Overcoming Objections','Part 3 — Hand them something','Selling Skills, Part 3','Multiple Choice','What are Mitch''s favorite things to hand a customer?','The multi-point inspection, a photo of the brake pads, an old filter, the alignment printout','A pen and a clipboard','The keys, briefly','A coffee','a','"Let them hold it... Now it''s their decision. They feel empowered again with real information in their hands."',2),
('AID:OO:M5:Q3','Overcoming Objections','Part 3 — Hand them something','Selling Skills, Part 3','True/False','True or False: If the customer isn''t in the lounge, the hand-them-something idea is dead.','True','False','','','b','"Send it, email it, text it — the video, the inspection, any photos — and number them in the sequence you''ll mention them."',3),
('AID:OO:M5:Q4','Overcoming Objections','Part 3 — Hand them something','Selling Skills, Part 3','What Do You Say Next','You''re in front of the customer with the inspection in hand. What do you say next?','"Let me read this to you."','"Hey, take a look." And let them hold it.','"I''ll file this for you."','"Don''t worry about the details."','b','"You''re not telling them what to do anymore. You''re sharing with them something about their vehicle."',4),
('AID:OO:M6:Q1','Overcoming Objections','Part 4 — We caught it in time','Selling Skills, Part 4','Multiple Choice','What does "we caught it in time" turn a brake job into?','A compliment — the customer''s habit of coming in is what saved them money','A discount request','An emergency','A bigger ticket','a','"That''s real money saved and it happened because of the habit."',1),
('AID:OO:M6:Q2','Overcoming Objections','Part 4 — We caught it in time','Selling Skills, Part 4','Multiple Choice','Who gets the credit?','The customer and their habit — they brought it back to you','You, for the sharp eye','Hector, for the measurement','The factory, for the interval','a','"Not you and not really even Hector... we are truly rewarding action."',2),
('AID:OO:M6:Q3','Overcoming Objections','Part 4 — We caught it in time','Selling Skills, Part 4','True/False','True or False: Resurfacing rotors instead of replacing them is real money the customer''s habit saved.','True','False','','','a','"Because this customer comes to you and you measure it every visit... those rotors are still good enough to resurface instead of replace."',3),
('AID:OO:M6:Q4','Overcoming Objections','Part 4 — We caught it in time','Selling Skills, Part 4','What Do You Say Next','The pads are worn but the rotors are still good. What do you say next?','"Your brakes are shot."','"Good news — because you bring your Camry here and Hector checks it every visit, we caught it in time and can resurface those rotors instead of replacing them."','"You got lucky this time."','"We can wait on all of it."','b','"It''s your job to share the good news."',4),
('AID:OO:M7:Q1','Overcoming Objections','Part 6 — The redirect and the dentist','Selling Skills, Part 6','Multiple Choice','What does the redirect — "I wouldn''t be doing my job if I didn''t share this with you" — accomplish?','It says maybe it''s me, maybe I didn''t share it well — which takes pressure off the customer and earns you one more try','It transfers blame to the technician','It restates the price','It ends the conversation politely','a','After the FIRST no — a redirect, never an argument.',1),
('AID:OO:M7:Q2','Overcoming Objections','Part 6 — The redirect and the dentist','Selling Skills, Part 6','Multiple Choice','What does a good dentist do when you decline the filling?','Shares what''s coming if it''s left ignored — once, calmly — and then lets you decide','Insists until you agree','Offers a discount','Says "okay, cool" and drops it','a','"They''re not being mean. They''re doing their job... So be more like a dentist."',2),
('AID:OO:M7:Q3','Overcoming Objections','Part 6 — The redirect and the dentist','Selling Skills, Part 6','True/False','True or False: "If left ignored..." frames the customer''s inaction as an action — and it''s stronger than "if you don''t do this..."','True','False','','','a','"Even when they''re not doing something, they''re still in an action" — the positive framing of a real consequence.',3),
('AID:OO:M7:Q4','Overcoming Objections','Part 6 — The redirect and the dentist','Selling Skills, Part 6','What Do You Say Next','The customer says "I''m going to think about it." What do you say next?','"Take all the time you need."','"Fair enough — one thing I''d share, like your dentist would: if left ignored, this gets worse. Then it''s completely your call."','"Thinking about it usually means no."','"What''s there to think about?"','b','Share what''s coming, once, calmly — then let them decide.',4),
('AID:OO:M8:Q1','Overcoming Objections','Part 7 — Information overload','Selling Skills, Part 7','Multiple Choice','What''s wrong with "is there anything I can do to make this easier for you?"','It hands away control — now they''re deciding whether you''re even useful','It''s too informal','It''s too long','Nothing — it''s the recommended line','a','"Stop. That question hands away control."',1),
('AID:OO:M8:Q2','Overcoming Objections','Part 7 — Information overload','Selling Skills, Part 7','Multiple Choice','What is "information overload"?','Giving so much good information — the scale, the measurement, the color, caught-in-time, the total, the time — that the conversation at home is easy','Burying the customer in technical jargon','Sending three brochures','Repeating the pitch twice','a','"The more information they bring home, the easier the yes, the more likely the yes."',2),
('AID:OO:M8:Q3','Overcoming Objections','Part 7 — Information overload','Selling Skills, Part 7','True/False','True or False: If the spouse is the decision maker, calling them yourself moves things along.','True','False','','','b','"Never ever ever call someone else''s spouse." Arm your customer and always let them make the call.',3),
('AID:OO:M8:Q4','Overcoming Objections','Part 7 — Information overload','Selling Skills, Part 7','What Do You Say Next','The customer says "I have to ask my wife." What do you say next?','"Is there anything I can do to make this easier?"','"Absolutely — before you call her, let me share a few details that make it simple: measured on a scale of 10 to 0, replace at 4, you''re at 3 — in the red — and we caught it in time, so we can resurface instead of replace."','"Should I call her for you?"','"Wives always say no."','b','Arm the customer so the conversation at home is: "sounds like you need it — do it."',4),
('AID:OO:M9:Q1','Overcoming Objections','Part 8 — The trade-in','Selling Skills, Part 8','Multiple Choice','"I''m trading it in by Christmas" — why fix it anyway?','The appraisal: they''ll knock value for everything it needs, often for more than the repair costs','Loyalty points transfer','The new dealer requires it','You can''t — let it go','a','"When it''s appraised, they''re gonna drive it, and if they feel weak brakes, they''re gonna ding you for those brakes."',1),
('AID:OO:M9:Q2','Overcoming Objections','Part 8 — The trade-in','Selling Skills, Part 8','Multiple Choice','So trading it in is...','Sometimes a reason TO get something done, not a reason to skip it','Always a lost sale','A bluff to call','A manager escalation','a','"Trading it in isn''t a reason to not get something done. It''s actually a reason to get something done."',2),
('AID:OO:M9:Q3','Overcoming Objections','Part 8 — The trade-in','Selling Skills, Part 8','True/False','True or False: The point of the trade-in conversation is education — either way, the customer hears it.','True','False','','','a','"Either way, the customer is gonna hear it. That''s the whole point. Education."',3),
('AID:OO:M9:Q4','Overcoming Objections','Part 8 — The trade-in','Selling Skills, Part 8','What Do You Say Next','"Why would I fix brakes on a truck I''m trading in?" What do you say next?','"You''re right, don''t bother."','"I totally understand — one thing to keep in mind: at appraisal they''ll drive it, and weak brakes often get dinged for more than the brakes cost."','"The next owner will thank you."','"Because safety."','b','Share the appraisal math and let them decide — that''s education, not pressure.',4),
('AID:OO:M10:Q1','Overcoming Objections','Part 9 — Read the customer','Selling Skills, Part 9','Multiple Choice','What are the two customers in this film?','The one who likes control ("if you HANDLE this today") and the passive one ("by LETTING US complete this today")','The buyer and the browser','New and repeat','Cash and financed','a','"Same close, same service, same price, but the doors into it are a little different."',1),
('AID:OO:M10:Q2','Overcoming Objections','Part 9 — Read the customer','Selling Skills, Part 9','Multiple Choice','How do you know which customer you''ve got?','Listen on the drive — they show you in the first two minutes','Ask them directly','Check their purchase history','Judge by the vehicle','a','"That''s why we got two ears and one mouth."',2),
('AID:OO:M10:Q3','Overcoming Objections','Part 9 — Read the customer','Selling Skills, Part 9','True/False','True or False: "By taking advantage of this today" works because everybody wants to feel like they''re getting a deal.','True','False','','','a','"That sentence is sharing with them that they''re getting a deal, man."',3),
('AID:OO:M10:Q4','Overcoming Objections','Part 9 — Read the customer','Selling Skills, Part 9','What Do You Say Next','On the drive the customer said "whatever you think is best." Which door do you choose at the close?','"If you handle this today..."','"By letting us complete this today..."','"You drive a hard bargain..."','"Take your time deciding..."','b','"Letting us, allowing us. Now it''s easy. They just have to say yes."',4),
('AID:OO:M11:Q1','Overcoming Objections','Part 10 — After the second no','Selling Skills, Part 10','Multiple Choice','After the second no, what does "giving up" actually mean?','Building the next visit — if it won''t wait 5,000 miles, set them up to come back in a thousand','Walking away silently','Noting it declined and moving on','One more try, gently','a','"You didn''t argue with the no, you just made sure the next conversation happened sooner than later."',1),
('AID:OO:M11:Q2','Overcoming Objections','Part 10 — After the second no','Selling Skills, Part 10','Multiple Choice','What is the takeaway close on a safety item?','"If you don''t do it here, please go do it somewhere else, because I want you safe." You gave up the sale out loud — and that''s exactly why it works','Removing the coupon from the offer','Taking the printout back','Silence until they crack','a','"The customer just heard that you care more about them than the money... even when they don''t say yes, they remember who said it."',2),
('AID:OO:M11:Q3','Overcoming Objections','Part 10 — After the second no','Selling Skills, Part 10','True/False','True or False: After the second no, you''re not selling anymore.','True','False','','','a','"You''re building the next visit."',3),
('AID:OO:M11:Q4','Overcoming Objections','Part 10 — After the second no','Selling Skills, Part 10','What Do You Say Next','Second no, and the item won''t safely wait 5,000 miles. What do you say next?','"Understood — see you at the next service."','"No problem at all. This one won''t wait 5,000 miles though — let''s set you up to come back in about a thousand, say three weeks."','"You''re making a mistake."','"Sign here that you declined."','b','No pressure, no shame — the next conversation just happens sooner.',4),
('AID:OO:M12:Q1','Overcoming Objections','The Steer Objection','Selling Skills, The Steer Objection','Multiple Choice','What are the primary five objections?','Money, time, decision maker, need, and going to take it somewhere else','Price, parts, people, process, promotion','Cost, color, calendar, convenience, confidence','Warranty, wait, wife, wallet, why','a','"You already know the primary five."',1),
('AID:OO:M12:Q2','Overcoming Objections','The Steer Objection','Selling Skills, The Steer Objection','Multiple Choice','Which two can you knock out of the park every single time?','Money — the financing link is already sent — and time, because your shuttle and ride share are already offered','Need and money','Decision maker and time','None; they''re all equally hard','a','"You''re ahead of the game" on those two before the objection ever lands.',2),
('AID:OO:M12:Q3','Overcoming Objections','The Steer Objection','Selling Skills, The Steer Objection','True/False','True or False: A great pitch steers the customer toward the objections you''ve already planned for.','True','False','','','a','"Don''t just prepare for them. Steer toward them."',3),
('AID:OO:M12:Q4','Overcoming Objections','The Steer Objection','Selling Skills, The Steer Objection','What Do You Say Next','A teammate asks: "how do I stop hearing I''m gonna take it somewhere else?" What do you say next?','"You can''t — some customers just leave."','"Make the relationship so strong it never comes up — and steer the conversation to the objections you''re most prepared for."','"Match whatever price they quote."','"Ask them where."','b','"Make the value so clear that I don''t need it is never said... What''s left is money and time, and those you''re most prepared for anyway."',4);

/* ---- NAME TAG — Parts 2-8 and 10 (1 and 9 carry the CSI seven) ---------- */
insert into _aid values
('AID:NT:P2:Q1','Name Tag','Part 2 — Always be right','Name Tag, Part 2','Multiple Choice','What''s the trust hack in this film?','Be right about the little things — people then assume you''re right about the big things','Dress sharper than the customer','Always agree with the customer','Talk fast and confident','a','Right about Hawaii''s little things, credited for Phoenix — "your customers do the exact same thing."',1),
('AID:NT:P2:Q2','Name Tag','Part 2 — Always be right','Name Tag, Part 2','Multiple Choice','What''s the born-on date fact you can share?','Tires carry a date on the sidewall — about six years on, it''s time to think about replacing them','Batteries expire five years from the sticker','Wipers age out in 18 months','Coolant is stamped under the cap','a','"Something true, something small, something they didn''t know" — and now you''re the person who knew.',2),
('AID:NT:P2:Q3','Name Tag','Part 2 — Always be right','Name Tag, Part 2','True/False','True or False: One wrong fact costs more than ten right ones earn.','True','False','','','a','"The one wrong fact, man, that''s the one everybody''s going to remember" — so check before you share.',3),
('AID:NT:P2:Q4','Name Tag','Part 2 — Always be right','Name Tag, Part 2','What Do You Say Next','You want to drop a little knowledge on the drive. What do you say next?','"Tires are complicated — trust me."','"Did you know your tires have a born-on date right on the sidewall?"','"I''ve been doing this twenty years."','"Your last shop missed a lot."','b','Small, true, and checkable — and when you later recommend the brake job, you''re the one who knew about the born-on date.',4),
('AID:NT:P3:Q1','Name Tag','Part 3 — The reveal','Name Tag, Part 3','Multiple Choice','"People don''t form loyalty to buildings." What do they form loyalty to?','People who feel like they care about them — the name tag is a promise','The lowest price in town','The closest location','The brand''s advertising','a','The four things on the tag are literally the four biggest reasons people come to you.',1),
('AID:NT:P3:Q2','Name Tag','Part 3 — The reveal','Name Tag, Part 3','Multiple Choice','If customers come for the brand, what do you do?','Say that brand name every chance you get','Stay neutral about brands','Push the extended warranty','Mention what the rivals lack','a','"If they come because of that brand, then say that brand name... people are so proud of the brands they drive."',2),
('AID:NT:P3:Q3','Name Tag','Part 3 — The reveal','Name Tag, Part 3','True/False','True or False: Your title obligates you to give advice, not just process tickets.','True','False','','','a','"Most of you are an advisor, so give advice. And your name — the reason somebody asks for you by name is you."',3),
('AID:NT:P3:Q4','Name Tag','Part 3 — The reveal','Name Tag, Part 3','What Do You Say Next','A teammate asks why they should write down the reasons people come here. What do you say next?','"It''s a corporate exercise."','"Look down at your shirt — dealership, brand, title, name. Those four ARE the reasons, literally."','"It fills the training hour."','"So the manager can grade it."','b','"Not in some abstract way, literally, it''s why they come to you."',4),
('AID:NT:P4:Q1','Name Tag','Part 4 — Dealership — why ain''t we?','Name Tag, Part 4','Multiple Choice','What''s wrong with "THEY sponsor a soccer team"?','It should be WE — put the shirt on, own the community work, make an impact','Sponsorships are a waste','It''s marketing''s job to answer','Nothing — it''s accurate','a','"Whoa, whoa, dog, they? Why ain''t it we? This is the moment I want you to be we."',1),
('AID:NT:P4:Q2','Name Tag','Part 4 — Dealership — why ain''t we?','Name Tag, Part 4','Multiple Choice','Why take a picture when your store sponsors the little league team?','You never know when that''s somebody''s niece or neighbor — put it behind your desk and let it make an impact','Social media policy requires it','Proof for the accounting office','It fills the wall','a','"When you do something good, take a picture... you made an impact on their family."',2),
('AID:NT:P4:Q3','Name Tag','Part 4 — Dealership — why ain''t we?','Name Tag, Part 4','True/False','True or False: "A lot of folks in our community take advantage of services just like this" — the word community builds a bond.','True','False','','','a','"It''s warm, it''s accurate, and it tells the customer that they belong to something."',3),
('AID:NT:P4:Q4','Name Tag','Part 4 — Dealership — why ain''t we?','Name Tag, Part 4','What Do You Say Next','A first responder is at your kiosk and your store runs a first-responder program. What do you say next?','Nothing — programs cheapen the visit','Share it — know your reputation story, your value packages, your programs for first responders and teachers','Mention it only if they ask','Refer them to the website','b','"Show people that your store cares. Word of mouth starts one person at a time."',4),
('AID:NT:P5:Q1','Name Tag','Part 5 — Brag on your brand','Name Tag, Part 5','Multiple Choice','When do we usually talk about our brand?','When times are bad — we gossip about it; when times are good we hardly say anything','Constantly, good or bad','Never — it''s unprofessional','Only at new-model launch','a','"Man, you''ve got good brands. Brag on them."',1),
('AID:NT:P5:Q2','Name Tag','Part 5 — Brag on your brand','Name Tag, Part 5','Multiple Choice','Before you share a piece of brand news with a customer, what''s the principle?','Check it before you say it — the one wrong fact is the one somebody looks up','Make it exciting, details later','Only repeat official press releases','Let the customer bring the news','a','"I checked it before I said it. That''s always a principle. You got to be right."',2),
('AID:NT:P5:Q3','Name Tag','Part 5 — Brag on your brand','Name Tag, Part 5','True/False','True or False: Learn about your brand the way your customers learn — YouTube and TikTok — because that''s where they''re learning about their own vehicle.','True','False','','','a','"If you don''t, the customers are going to know stuff you don''t know" — and not everything on the internet is true, so you''re the filter.',3),
('AID:NT:P5:Q4','Name Tag','Part 5 — Brag on your brand','Name Tag, Part 5','What Do You Say Next','A customer mentions their spouse just bought a new Bronco. What do you say next?','"Nice. Anyway, about your brakes..."','Share something cool and TRUE about the brand that you verified recently','Recite the full spec sheet','"Fords have problems, between us."','b','Be the person who shares what the manufacturer is doing — verified first, always.',4),
('AID:NT:P6:Q1','Name Tag','Part 6 — You are not a financial advisor','Name Tag, Part 6','Multiple Choice','What does "don''t sell out of the customer''s wallet" mean?','You don''t know what''s a lot of money to somebody else or what they value — offer everything appropriate and let them decide','Skip financing talk','Discount early and often','Run a credit check first','a','"You do not know what people will spend their money on... So stop deciding for them."',1),
('AID:NT:P6:Q2','Name Tag','Part 6 — You are not a financial advisor','Name Tag, Part 6','Multiple Choice','What''s the point of the DirecTV story?','A family with no siding on the house spent $1,500 on a satellite dish to watch the Cowboys — you cannot predict what people will spend on what they love','Budgeting matters','Satellite TV was overpriced','Sports fans overspend','a','"We didn''t have money for siding. But he spent fifteen hundred dollars on a satellite dish."',2),
('AID:NT:P6:Q3','Name Tag','Part 6 — You are not a financial advisor','Name Tag, Part 6','True/False','True or False: If money looks tight for a customer, trim the recommendations before presenting them.','True','False','','','b','Deciding for them is exactly the mistake — "offer everything that''s appropriate and let them decide."',3),
('AID:NT:P6:Q4','Name Tag','Part 6 — You are not a financial advisor','Name Tag, Part 6','What Do You Say Next','A teammate says "I didn''t offer the alignment — that guy can''t afford it." What do you say next?','"Good read."','"You''re a service advisor, not a financial advisor — offer it and let him decide."','"Offer half of it."','"Note it for next time instead."','b','"You don''t know what''s in their wallet. You don''t know what they find valuable."',4),
('AID:NT:P7:Q1','Name Tag','Part 7 — Give real advice','Name Tag, Part 7','Multiple Choice','What are the three things to share with a young driver?','Listen to you, listen to the vehicle, and listen to the certified technician','Drive slow, keep receipts, rotate tires','Read the manual, check the app, call the factory','Buy the warranty, wash it weekly, use premium','a','"Listen to me. Listen to the vehicle. Listen to the certified technician."',1),
('AID:NT:P7:Q2','Name Tag','Part 7 — Give real advice','Name Tag, Part 7','Multiple Choice','What register should advice be given in?','Like you''re talking to an eight-year-old or an 88-year-old — universal, straightforward, never scary','Technical, to establish credibility','Match their vocabulary exactly','Quick, to respect their time','a','"You wouldn''t be technical... you wouldn''t be harsh. You would make it straightforward and easy to understand."',2),
('AID:NT:P7:Q3','Name Tag','Part 7 — Give real advice','Name Tag, Part 7','True/False','True or False: Reward action before you punish inaction — positive first, negative last and only if you need it.','True','False','','','a','"A complete brake job will help your vehicle stop better" — not "if you don''t do this, you''re going to crash."',3),
('AID:NT:P7:Q4','Name Tag','Part 7 — Give real advice','Name Tag, Part 7','What Do You Say Next','You''re teaching a new driver about warning lights. What''s the instruction you hope ends every one?','"Look it up online."','"When that light comes on — call me."','"Keep driving to a safe distance."','"Check the manual first."','b','"Share the main warning lights by heart... and inside all of those instructions, what I hope you say is: call me. Own it."',4),
('AID:NT:P8:Q1','Name Tag','Part 8 — You are the reason','Name Tag, Part 8','Multiple Choice','What''s the gas-pump test?','The customer should think of you at the pump — "if I put cheap gas in, my advisor''s going to be on my butt about it"','Your store should sponsor pump ads','Fuel additives sell at the pump','Gas prices drive service traffic','a','"That''s how ingrained you should be in their automobile space."',1),
('AID:NT:P8:Q2','Name Tag','Part 8 — You are the reason','Name Tag, Part 8','Multiple Choice','What are the clues to look for on the drive?','The radio station, bumper stickers, a hat, a car seat, a golf bag — every one a doorway into a real conversation','Tire wear patterns','The fuel level','Trade-in value signals','a','"Find common ground, build the relationship and be their one vendor for their automotive needs."',2),
('AID:NT:P8:Q3','Name Tag','Part 8 — You are the reason','Name Tag, Part 8','True/False','True or False: "I only want you to sell two things all day, every day: yourself and your team." Everything else is just offerings.','True','False','','','a','And make it easy to reach you — circle your direct line, push everybody toward text.',3),
('AID:NT:P8:Q4','Name Tag','Part 8 — You are the reason','Name Tag, Part 8','What Do You Say Next','There''s a softball bat in the back seat. What do you say next?','"I''ll move this for you."','"You got a bat in there — do you play in a league?"','"Please clear the vehicle next time."','"Nice bat. Anyway — your filters."','b','Every clue is a doorway into a real conversation — common ground first.',4),
('AID:NT:P10:Q1','Name Tag','Part 10 — Log it, reset it, own it','Name Tag, Part 10','Multiple Choice','What does "log it" mean?','Drop personal details into the system''s notes so next visit you can say "tough loss for the Aggies Saturday"','Log your hours precisely','Log every declined item','Keep a paper journal','a','"It shows them that you listened" — and the system reminds you when memory won''t.',1),
('AID:NT:P10:Q2','Name Tag','Part 10 — Log it, reset it, own it','Name Tag, Part 10','Multiple Choice','What is the mid-day reset?','Look down at your name tag, pick one element — dealership, brand, title, name — and really talk to the next customer about it','A coffee break at noon','Re-reading the morning''s ROs','A team huddle','a','"It''s right there on your shirt all day long."',2),
('AID:NT:P10:Q3','Name Tag','Part 10 — Log it, reset it, own it','Name Tag, Part 10','True/False','True or False: "This is the owner''s business, not mine" is the right way to think about your kiosk.','True','False','','','b','"You''re wrong, man. This is your business" — a career, your personal business, your own self-determination.',3),
('AID:NT:P10:Q4','Name Tag','Part 10 — Log it, reset it, own it','Name Tag, Part 10','What Do You Say Next','A customer mentions their daughter just started college. What do you do before the next customer walks up?','Nothing — small talk is small talk','Put it in the system''s special instructions so next visit starts with "how''s your daughter liking school?"','Tell a teammate','Write it on a sticky note for later','b','Mitch got chastised over a note he didn''t write down sixteen years ago — "if you can, put it in the system so you''re reminded."',4);

/* ===========================================================================
   STAGE -> BANK, WITH THE GUARDS
   =========================================================================== */
do $$
declare
  _n int;
  _r record;
begin
  select count(*) into _n from _aid;
  if _n <> 184 then
    raise exception '0146: staged % rows, expected 184 (46 modules x 4)', _n;
  end if;

  /* Local replay: the films are not there, and this is a quiet no-op. */
  if not exists (select 1 from content
                  where title = 'Get the Hell Out of Here, Part 1'
                    and type = 'advisor_video' and status = 'published'
                    and retired_at is null and module_id is not null) then
    raise notice '0146: the routed films are not present on this database — nothing to do';
    return;
  end if;

  /* Idempotent on source_id, 0140''s way. */
  select count(*) into _n from quiz_question where source_id like 'AID:%';
  if _n = 184 then
    raise notice '0146: all 184 drafts already present — nothing to add';
    return;
  end if;
  if _n <> 0 then
    raise exception '0146: % of 184 already present — refusing a partial re-import', _n;
  end if;

  insert into quiz_question (
    source_id, deck, film, question, option_a, option_b, option_c, option_d,
    correct, explanation, sort_order, status, source, question_type,
    shared_pool, module_id, content_id
  )
  select a.source_id, a.deck, a.film, a.question,
         a.option_a, a.option_b, a.option_c, a.option_d,
         a.correct, a.explanation, a.qno, 'draft', 'ai_generated', a.qtype,
         false, c.module_id, c.id
    from _aid a
    join content c
      on c.title = a.film_title
     and c.type = 'advisor_video'
     and c.status = 'published'
     and c.retired_at is null
     and c.module_id is not null;

  get diagnostics _n = row_count;
  if _n <> 184 then
    raise exception '0146: inserted % rows, expected 184 — a film title failed to join', _n;
  end if;

  /* ---- ASSERT, BOTH DIRECTIONS ------------------------------------------ */

  /* exactly 4 per module, over exactly 46 modules */
  select count(*) into _n from (
    select module_id from quiz_question where source_id like 'AID:%'
    group by module_id having count(*) <> 4
  ) bad;
  if _n <> 0 then
    raise exception '0146: % module(s) did not receive exactly 4 drafts', _n;
  end if;
  select count(distinct module_id) into _n from quiz_question where source_id like 'AID:%';
  if _n <> 46 then
    raise exception '0146: drafts landed on % modules, expected 46', _n;
  end if;

  /* every draft''s module is its film''s module */
  select count(*) into _n
    from quiz_question q join content c on c.id = q.content_id
   where q.source_id like 'AID:%' and c.module_id is distinct from q.module_id;
  if _n <> 0 then
    raise exception '0146: % draft(s) point at a different module than their film', _n;
  end if;

  /* NOTHING PUBLISHED. The bank the advisors see is exactly what 0145 left. */
  select count(*) into _n from quiz_question where status = 'published';
  if _n <> 112 then
    raise exception '0146: published count moved to % — drafts must not publish', _n;
  end if;
  select count(*) into _n from quiz_question
   where source_id like 'AID:%' and (status <> 'draft' or source <> 'ai_generated');
  if _n <> 0 then
    raise exception '0146: % draft row(s) with wrong status or source', _n;
  end if;

  /* every module set carries at least one scenario question */
  select count(*) into _n from (
    select module_id from quiz_question where source_id like 'AID:%'
    group by module_id
    having count(*) filter (where question_type = 'What Do You Say Next') = 0
  ) noscenario;
  if _n <> 0 then
    raise exception '0146: % module(s) have no scenario question', _n;
  end if;

  raise notice '0146: 184 drafts staged for Mitch — 36 Setting up the MPI, 48 Success Cycle, 40 Overcoming Objections, 32 Name Tag, 28 Menus. Nothing published.';
end
$$;
